"use client";
import { useEffect,useMemo,useState } from "react";
type Row={condition:string;product:string;ai_disclosure:number;pilot:number;started_at:string|null;completed_at:string|null;status:string;duration_seconds:number|null;attention_passed:number|null;manipulation_passed:number|null;invalid_reason:string|null;answers:Record<string,string>};
const C=["laptop_ai","laptop_no_ai","beverage_ai","beverage_no_ai"],CN:Record<string,string>={laptop_ai:"Laptop · AI",laptop_no_ai:"Laptop · No AI",beverage_ai:"Beverage · AI",beverage_no_ai:"Beverage · No AI"};
const Q:Record<string,string>={consent:"Consent",q1:"Age",q2:"E-commerce usage",q3:"Recent product browsing",q4:"Purchase involvement",q5:"Brand comparison",...Object.fromEntries(Array.from({length:28},(_,i)=>[`q${i+6}`,`${["Competence","Novelty","Authenticity","Humanness","Legitimacy","Trust","Purchase intention"][Math.floor(i/4)]} ${i%4+1}`])),q34:"Attention check",q35:"Manipulation check",q36:"AI attitude",q37:"AI tool usage",q38:"Brand familiarity",q39:"Previous purchase",q40:"Detail-page reading",q41:"Gender",q42:"Education",q43:"Current status",q44:"Disposable income"};
const N:Record<string,string>={agree:"Agree",disagree:"Disagree",under18:"Under 18","18-25":"18–25","26-35":"26–35","36-45":"36–45","46+":"46+",frequently:"Frequently",occasionally:"Occasionally",rarely:"Rarely",almost_never:"Almost never",yes:"Yes",no:"No",not_sure:"Not sure",ai_used:"AI stated",no_information:"No AI information",do_not_remember:"Do not remember",male:"Male",female:"Female",other:"Other / Prefer not",high_school:"High school or below",associate:"Associate",bachelor:"Bachelor",master_plus:"Master+",student:"Student",employee:"Employee",freelancer:"Freelancer",not_employed:"Not employed",under3000:"< 3,000","3000_5999":"3,000–5,999","6000_9999":"6,000–9,999","10000_plus":"10,000+",prefer_not:"Prefer not",completed:"Completed",invalid:"Invalid",in_progress:"In progress",passed:"Passed",failed:"Failed",not_recorded:"Not recorded",underage:"Under age",attention:"Attention check",not_invalid:"Not invalid"};
const pct=(n:number,d:number)=>d?`${(n*100/d).toFixed(1)}%`:"0.0%";
const counts=(rows:Row[],fn:(r:Row)=>string)=>rows.reduce<Record<string,number>>((o,r)=>{const k=fn(r);o[k]=(o[k]||0)+1;return o},{});
function Bars({data,total,amber=false}:{data:Record<string,number>;total:number;amber?:boolean}){const items=Object.entries(data).sort((a,b)=>b[1]-a[1]);return items.length?<>{items.map(([k,n])=><div className="bar-row" key={k}><span>{N[k]||CN[k]||k}</span><div className="bar-track"><div className={`bar-fill ${amber?"amber":""}`} style={{width:`${total?n*100/total:0}%`}}/></div><span className="bar-value">{n} · {pct(n,total)}</span></div>)}</>:<div className="empty">暂无数据</div>}
function Metric({label,value,note}:{label:string;value:string|number;note:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
export default function Dashboard(){
 const [token,setToken]=useState(""),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[rows,setRows]=useState<Row[]>([]),[view,setView]=useState("overview"),[status,setStatus]=useState("all"),[condition,setCondition]=useState("all"),[pilot,setPilot]=useState("main"),[updated,setUpdated]=useState(""),[question,setQuestion]=useState("q1"),[identity,setIdentity]=useState("q1"),[outcome,setOutcome]=useState("q30");
 useEffect(()=>{const saved=sessionStorage.getItem("qi_token");if(saved)setToken(saved)},[]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username,password})}),v=await r.json();if(!r.ok)throw new Error(v.error);sessionStorage.setItem("qi_token",v.token);setToken(v.token)}catch(e){setError(e instanceof Error?e.message:"登录失败")}finally{setBusy(false)}}
 const filtered=useMemo(()=>rows.filter(r=>(status==="all"||r.status===status)&&(condition==="all"||r.condition===condition)&&(pilot==="all"||(pilot==="pilot"?+r.pilot===1:+r.pilot===0))),[rows,status,condition,pilot]);
 function logout(){sessionStorage.removeItem("qi_token");setToken("");setRows([]);setPassword("")}
 async function importFile(file:File){setError("");try{const text=await file.text(),trimmed=text.trim();const raw:unknown[]=trimmed.startsWith("[")?JSON.parse(trimmed):trimmed.split(/\r?\n/).filter(Boolean).map(line=>JSON.parse(line));const parsed=raw.map((item:any)=>item?.data?.id?item.data:item).filter((item:any)=>item&&item.condition&&item.answers).map((item:any)=>({...item,ai_disclosure:item.condition==="laptop_ai"||item.condition==="beverage_ai"?1:0}));if(!parsed.length)throw new Error("文件中没有可识别的问卷记录");setRows(parsed);setUpdated(new Date().toLocaleString())}catch(e){setRows([]);setError(e instanceof Error?`导入失败：${e.message}`:"导入失败")}}
 function exportCsv(){const keys=["condition","product","ai_disclosure","pilot","status","started_at","completed_at","duration_seconds","attention_passed","manipulation_passed","invalid_reason","consent",...Array.from({length:44},(_,i)=>`q${i+1}`)],quote=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`,csv=[keys.join(","),...filtered.map(r=>keys.map(k=>quote(Object.prototype.hasOwnProperty.call(r,k)?r[k as keyof Row]:r.answers?.[k])).join(","))].join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=`questionnaire-data-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
 if(!token)return <main className="login-shell"><section className="login-card"><div className="brand-mark">QI</div><p className="eyebrow">RESEARCH OPERATIONS</p><h1>Questionnaire Insights</h1><p className="lede">问卷数据的安全可视化后台</p><form onSubmit={login}><label>用户名</label><input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required/><label>密码</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><button disabled={busy}>{busy?"正在登录…":"登录后台"}</button><p className="error">{error}</p></form><p className="security-note">数据仅在登录后加载，本页不会保存管理员密码。</p></section></main>;
 const completed=filtered.filter(r=>r.status==="completed").length,invalid=filtered.filter(r=>r.status==="invalid").length,durations=filtered.map(r=>Number(r.duration_seconds)).filter(n=>n>0),avg=durations.length?Math.round(durations.reduce((a,b)=>a+b,0)/durations.length):0,answered=filtered.filter(r=>r.answers?.[question]!=null),ids=[...new Set(filtered.map(r=>r.answers?.[identity]).filter(Boolean))],outs=[...new Set(filtered.map(r=>r.answers?.[outcome]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));
 return <main className="dashboard"><aside className="sidebar"><div className="logo-row"><span className="brand-mark small">QI</span><strong>Questionnaire<br/>Insights</strong></div><nav>{[["overview","总览"],["questions","逐题分析"],["crosstab","身份交叉"],["quality","数据质量"]].map(([id,label])=><button key={id} className={`nav-item ${view===id?"active":""}`} onClick={()=>setView(id)}>{label}</button>)}</nav><button className="logout" onClick={logout}>退出登录</button></aside><section className="workspace"><header className="topbar"><div><p className="eyebrow">2 × 2 EXPERIMENT</p><h1>{{overview:"研究数据总览",questions:"逐题选择率",crosstab:"身份交叉分析",quality:"数据质量检查"}[view]}</h1></div><div className="top-actions"><label className="import-button">导入腾讯云 JSON<input type="file" accept=".json,application/json" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/></label><button onClick={exportCsv} disabled={!rows.length}>导出当前数据</button></div></header><section className="filters"><label>样本状态<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option><option value="completed">仅完成</option><option value="invalid">仅作废</option><option value="in_progress">进行中</option></select></label><label>实验条件<select value={condition} onChange={e=>setCondition(e.target.value)}><option value="all">全部条件</option>{C.map(c=><option key={c} value={c}>{CN[c]}</option>)}</select></label><label>数据类型<select value={pilot} onChange={e=>setPilot(e.target.value)}><option value="main">正式数据</option><option value="pilot">预测试</option><option value="all">全部</option></select></label><span className="updated">{updated?`本地导入于 ${updated}`:"请先导入腾讯云导出的 JSON 文件"}</span></section>{error&&<p className="error">{error}</p>}
 {view==="overview"&&<><section className="metrics"><Metric label="全部记录" value={filtered.length} note="当前筛选范围"/><Metric label="完成问卷" value={completed} note={pct(completed,filtered.length)}/><Metric label="作废记录" value={invalid} note={pct(invalid,filtered.length)}/><Metric label="平均用时" value={avg?`${Math.floor(avg/60)}m ${avg%60}s`:"—"} note="仅含已计时记录"/></section><section className="grid-2"><article className="panel"><h2>四组样本分配</h2><Bars data={counts(filtered,r=>r.condition)} total={filtered.length}/></article><article className="panel"><h2>答题状态</h2><Bars data={counts(filtered,r=>r.status)} total={filtered.length} amber/></article></section></>}
 {view==="questions"&&<article className="panel"><div className="toolbar"><label>选择题目<select value={question} onChange={e=>setQuestion(e.target.value)}>{Object.entries(Q).map(([k,v])=><option key={k} value={k}>{k.toUpperCase()} · {v}</option>)}</select></label><span className="pill">{answered.length} answered</span></div><h2>{question.toUpperCase()} · {Q[question]}</h2><Bars data={counts(answered,r=>String(r.answers[question]))} total={answered.length}/></article>}
 {view==="crosstab"&&<article className="panel"><div className="toolbar"><label>身份变量<select value={identity} onChange={e=>setIdentity(e.target.value)}>{["q1","q41","q42","q43","q44"].map(k=><option key={k} value={k}>{Q[k]}</option>)}</select></label><label>对比题目<select value={outcome} onChange={e=>setOutcome(e.target.value)}>{Object.entries(Q).filter(([k])=>k!=="consent").map(([k,v])=><option key={k} value={k}>{k.toUpperCase()} · {v}</option>)}</select></label></div><h2>{Q[identity]} × {Q[outcome]}</h2>{ids.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>{Q[identity]}</th>{outs.map(v=><th key={v}>{N[v]||v}</th>)}<th>Total</th></tr></thead><tbody>{ids.map(iv=>{const group=filtered.filter(r=>r.answers?.[identity]===iv&&r.answers?.[outcome]!=null),cs=counts(group,r=>r.answers[outcome]);return <tr key={iv}><td><strong>{N[iv]||iv}</strong></td>{outs.map(v=><td key={v}>{cs[v]||0} <small>({pct(cs[v]||0,group.length)})</small></td>)}<td>{group.length}</td></tr>})}</tbody></table></div>:<div className="empty">暂无可交叉分析的数据</div>}</article>}
 {view==="quality"&&<section className="grid-2"><article className="panel"><h2>注意力检查</h2><Bars data={counts(filtered,r=>r.attention_passed==null?"not_recorded":r.attention_passed?"passed":"failed")} total={filtered.length}/></article><article className="panel"><h2>操纵检查</h2><Bars data={counts(filtered,r=>r.manipulation_passed==null?"not_recorded":r.manipulation_passed?"passed":"failed")} total={filtered.length}/></article><article className="panel"><h2>作废原因</h2><Bars data={counts(filtered,r=>r.invalid_reason||"not_invalid")} total={filtered.length}/></article><article className="panel"><h2>异常短时长</h2><Metric label="少于 60 秒完成" value={filtered.filter(r=>Number(r.duration_seconds)>0&&Number(r.duration_seconds)<60).length} note="正式分析前请预先确定阈值"/></article></section>}</section></main>
}
